server.port=8881
management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
management.endpoint.shutdown.enabled=true

logging.level.org.springframework=debug
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver





